version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: c_nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/html/
    ports:
      - 80:80
    networks:
      - site1
networks:
  site1:
    external:
      name: nextjs_web