version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/html/
    ports:
      - "80:80"
    networks:
      - nextjs-docker
networks:
  nextjs-docker:
    external:
      name: nextjs-docker_default